<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="my_bot">

  <!-- ────────────  Global constants based on engineering drawing ──────────── -->
  <xacro:property name="wheel_radius" value="0.06"/>  <!-- 120mm diameter / 2 -->
  <xacro:property name="wheel_width"  value="0.01"/>  <!-- Estimated from diagram -->
  <xacro:property name="wheel_base"   value="0.2"/>   <!-- 200mm width -->
  <xacro:property name="base_length"  value="0.2"/>   <!-- 200mm length -->
  <xacro:property name="base_width"   value="0.2"/>   <!-- 200mm width -->
  <xacro:property name="base_height"  value="0.1"/>   <!-- 100mm height -->
  <xacro:property name="caster_radius" value="0.021"/> <!-- R21 in diagram -->

  <!-- ────────────  Materials  ──────────── -->
  <material name="Black"><color rgba="0 0 0 1.0"/></material>
  <material name="Blue"><color  rgba="0 0 1 1.0"/></material>
  <material name="Gray"><color  rgba="0.4 0.4 0.4 1.0"/></material>
  <material name="Red"><color   rgba="1 0 0 1.0"/></material>
  <material name="White"><color rgba="1 1 1 1.0"/></material>
  <material name="Orange"><color rgba="1 0.5 0 1.0"/></material>
  <material name="Green"><color rgba="0 1 0 1.0"/></material>

  <!-- ────────────  Dummy root to satisfy KDL  ──────────── -->
  <link name="root_link"/>
  <joint name="root_to_base" type="fixed">
    <parent link="root_link"/>
    <child  link="base_link"/>
  </joint>

  <!-- ────────────  Base chassis  ──────────── -->
  <link name="base_link">
    <visual>
      <!-- Offset base visual to raise the robot so wheels touch ground -->
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
      <material name="Blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <inertia 
        ixx="0.1" ixy="0.0" ixz="0.0"
        iyy="0.1" iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <!-- Base link gazebo material -->
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
    <mu1>0.5</mu1>
    <mu2>0.5</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
  </gazebo>

  <!-- ────────────  Wheels - positioned per diagram ──────────── -->
  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <inertia 
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_left_link"/>
    <!-- Positioned on side of robot, centered vertically -->
    <origin xyz="0 ${wheel_base/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Left wheel gazebo material -->
  <gazebo reference="wheel_left_link">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
  </gazebo>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <inertia 
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>
  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_right_link"/>
    <!-- Positioned on side of robot, centered vertically -->
    <origin xyz="0 -${wheel_base/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right wheel gazebo material -->
  <gazebo reference="wheel_right_link">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
  </gazebo>

  <!-- ────────────  Passive caster positioned per drawing ──────────── -->
  <link name="caster_link">
    <visual>
      <geometry><sphere radius="${caster_radius}"/></geometry>
      <material name="Gray"/>
    </visual>
    <collision>
      <geometry><sphere radius="${caster_radius}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia 
        ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0"
        izz="0.001"/>
    </inertial>
  </link>
  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="caster_link"/>
    <!-- Position the caster at the front as shown in diagram -->
    <origin xyz="${base_length/2 - 0.039} 0 -${caster_radius - 0.005}" rpy="0 0 0"/>
  </joint>

  <!-- Caster gazebo material -->
  <gazebo reference="caster_link">
    <material>Gazebo/Gray</material>
    <mu1>0.01</mu1>
    <mu2>0.01</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
  </gazebo>

  <!-- ────────────  LIDAR  ──────────── -->
  <link name="lidar_link">
    <visual>
      <geometry><cylinder radius="0.05" length="0.025"/></geometry>
      <material name="Orange"/>
    </visual>
    <collision>
      <geometry><cylinder radius="0.05" length="0.025"/></geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia 
        ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0"
        izz="0.001"/>
    </inertial>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius + 0.05}" rpy="0 0 0"/>
  </joint>

  <!-- Lidar gazebo material -->
  <gazebo reference="lidar_link">
    <material>Gazebo/Orange</material>
  </gazebo>

  <!-- ────────────  RGB Camera  ──────────── -->
  <link name="camera_link">
    <visual>
      <geometry><box size="0.02 0.02 0.01"/></geometry>
      <material name="Red"/>
    </visual>
    <collision>
      <geometry><box size="0.02 0.02 0.01"/></geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <inertia 
        ixx="0.000001" ixy="0.0" ixz="0.0"
        iyy="0.000001" iyz="0.0"
        izz="0.000001"/>
    </inertial>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="camera_link"/>
    <origin xyz="${base_length/2} 0.0 ${wheel_radius + base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Camera gazebo material -->
  <gazebo reference="camera_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- Gazebo plugin for ROS2 control -->
  <gazebo>
    <plugin filename="libignition-gazebo-diff-drive-system.so" name="ignition::gazebo::systems::DiffDrive">
      <left_joint>wheel_left_joint</left_joint>
      <right_joint>wheel_right_joint</right_joint>
      <wheel_separation>${wheel_base}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_topic>odom</odom_topic>
      <max_linear_acceleration>1</max_linear_acceleration>
      <max_angular_acceleration>2</max_angular_acceleration>
      <min_linear_velocity>-1</min_linear_velocity>
      <max_linear_velocity>1</max_linear_velocity>
      <min_angular_velocity>-2</min_angular_velocity>
      <max_angular_velocity>2</max_angular_velocity>
    </plugin>
  </gazebo>

</robot>